version: '{build}'
branches:
  only:
  - master
max_jobs: 1
image: Ubuntu
clone_depth: 1
clone_folder: /home/appveyor/projects/foe_arc_calculator
environment:
  sftphost:
    secure: K+IBdbzrGeOB6TrWoKfjH7daOWKHdi1NC29EQpFWM6Q=
  sftpuser:
    secure: 4jzAsotRo+B96+sS3FGYLQ==
  sftppass:
    secure: sU0NNi4jJPIMPAVGdZJRNWMHakjxC7o6VibAycAGN7c=
build: off
deploy_script:
- sh: >-
    git clone https://github.com/clarkwang/passh.git /home/appveyor/projects/passh

    cd /home/appveyor/projects/passh

    make

    cd /home/appveyor/projects/foe_arc_calculator

    wget https://code.jquery.com/jquery-3.3.1.slim.min.js

    rm -rf .git

    echo -e "cd www\ncd arc" > sftp

    ls *.html *.css *.js *.json | while FILE; do echo -e "put ${FILE}" >> sftp; done

    /home/appveyor/projects/passh/passh -p $sftppass bash -c "sftp -o BatchMode=no -o StrictHostKeyChecking=no -b sftp $sftpuser@$sftphost"
